item_max: 20
media_path: ./media
url_base: http://wpc5001.cs.oki.co.jp:6680/media
email: sawai687@oki.com(sawai)
title: myfeed
link: http://wpc5001.cs.oki.co.jp:6680/
description: teto's audio
category: Music
language: ja
copyright: teto
generator: dir2feed
ttl: 60
itunes_author: teto
itunes_subtitle: teto's audio
itunes_category: Music
itunes_subcategory: Music Commentary
itunes_summary: radio
itunes_keywords: teto
itunes_explicit: clean
image_url: wpc5001.cs.oki.co.jp:6680/dir2feed_logo.jpg
image_title: dir2feed_logo
